### PR TITLE
Sonatype OSSRH support

### PR DESCRIPTION
**Pull request by chrismattmann**
support to publish to sonatype

### CODE REVIEW

**Comment by smadha** [comment]
@manalishah @chrismattmann You want to use enforcer-plugin here too?

**Comment by chrismattmann** [comment]
sure @smadha should we not?

**Comment by smadha** [comment]
@chrismattmann well that would disallow people from using jdk8. I think at some point we need to move to 8, it's almost 2 years since it's launched. Also as it's a new codebase so I thought using latest would be better.

Unless you think it will be incompatible with Tika.

**Comment by chrismattmann** [comment]
@smadha agreed. can you please submit a pR that removes that check? we want to support 8 too but not require it.

**Comment by smadha** [comment]
@chrismattmann Done - https://github.com/manalishah/NLTKRest/pull/10

Test code in comments

**Pull request merged**
